name: nn_bo
channels:
  - conda-forge
  - gpytorch
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.12.4
  - botorch=0.11.1
  - matplotlib==3.8.4
  - torchaudio==2.3.1
  - pytorch-cuda=12.1
  - torchvision==0.18.1
  - pytorch=2.3.1
  - numpy==1.26.4
  - scipy==1.15.2
