name: nn_bo
channels:
  - conda-forge
  - gpytorch
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - botorch=0.11.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - expat=2.6.4
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gpytorch=1.11
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jaxtyping=0.2.9
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.7
  - linear_operator=0.5.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mysql=8.4.0
  - ncurses=6.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - opt_einsum=3.3.0
  - pcre2=10.42
  - pixman=0.40.0
  - pyqt=6.7.1
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - python=3.12.4
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.14
  - typeguard=2.13.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - brotli==1.0.9
    - certifi==2025.1.31
    - contourpy==1.3.1
    - filelock==3.17.0
    - fonttools==4.55.3
    - gmpy2==2.2.1
    - idna==3.7
    - jinja2==3.1.6
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.8.4
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multipledispatch==0.6.0
    - networkx==3.4.2
    - numpy==1.26.4
    - packaging==24.2
    - pillow==11.1.0
    - pip==25.0
    - pyparsing==3.0.9
    - pyqt6==6.7.1
    - pyqt6-sip==13.9.1
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.2
    - requests==2.32.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - setuptools==75.8.0
    - sip==6.10.0
    - six==1.17.0
    - sympy==1.13.3
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - torch==2.3.1
    - torchaudio==2.3.1
    - torchvision==0.18.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - unicodedata2==15.1.0
    - urllib3==2.3.0
    - wheel==0.45.1
