parameters:
  acquisition_dataset:
    parameters:
      expansion_factor:
        value: 2
      max_history:
        value: 400
      min_history:
        value: 1
      n_candidates:
        value: 1
  architecture:
    parameters:
      layer_width:
        value: 250
      standardize_nn_history_outcomes:
        value: false
  function_samples_dataset:
    parameters:
      dimension:
        value: 8
      kernel:
        value: Matern52
      lengthscale:
        value: 0.1
      outcome_transform:
        values:
        - null
        - parameters:
            sigma:
              value: 0.8
          value: exp
      randomize_params:
        value: false
      standardize_outcomes:
        value: false
      test_samples_size:
        value: 5000
      train_samples_size:
        values:
        - 1000
        - 10000
        - 100000
  training:
    parameters:
      batch_size:
        value: 32
      learning_rate:
        value: 0.003
      method:
        value:
          parameters:
            lamda_config:
              parameters:
              - lamda_max:
                  value: 1.0
                lamda_min:
                  value: 0.0001
            normalize_gi_loss:
              value: true
          value: gittins
