parameters:
  objectives:
    parameters:
      dimension:
        values: [8, 16, 32]
      kernel:
        values: ["Matern52"]
      lengthscale:
        values: [0.1]
      randomize_params:
        values: [false, true]
      outcome_transform:
        values:
        - value: null
        - value: exp
          parameters:
            sigma:
              value: 0.8
      n_functions:
        value: 16
  n_iter:
    value: 200
  seed:
    value: 12
  n_trials_per_function:
    value: 1
  n_initial_samples:
    value: 1
  gp_af:
    parameters:
      af:
        values: ['LogEI']
      fit:
        values: ['none', 'map', 'mle']
