parameters:
  max_history:
    value: 20
  method:
    value: gittins
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.e-4
  train_samples_size:
    value: 100000
  layer_width:
    value: 512
  dimension:
    value: 16
  learning_rate:
    value: 3.e-4
  patience:
    value: 100
  epochs:
    value: 1000
  learning_rate:
    value: 1.e-5
