parameters:
  max_history:
    value: 20
  dimension:
    value: 8
  lengthscale:
    value: 0.49
  method:
    value: gittins
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.00e-02
  train_samples_size:
    values: [10, 40, 160, 640]
  samples_addition_amount:
    values: [5, 10, 20, 40, 1000]
  layer_width:
    value: 300
  epochs:
    value: 10000
  learning_rate:
    value: 3.00e-04
  batch_size:
    value: 512
  lr_scheduler:
    value: null
  early_stopping:
    value: true
  patience:
    value: 3000
