parameters:
  max_history:
    value: 20
  dimension:
    value: 8
  lengthscale:
    values: [0.25, 0.49]
  method:
    values: ['gittins', 'mse_ei']
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.00e-02
  train_samples_size:
    values: [160, 640, 2560]
  samples_addition_amount:
    values: [250, 1000, 4000]
  test_samples_size:
    value: 1000
  test_expansion_factor:
    value: 100
  layer_width:
    value: 300
  epochs:
    value: 10000
  learning_rate:
    values: [5.20e-05, 3.00e-04, 1.73e-03, 1.00e-02]
  batch_size:
    value: 512
  lr_scheduler:
    values: [null, 'ReduceLROnPlateau']
  lr_scheduler_patience:
    value: 300
  lr_scheduler_factor:
    value: 0.5
  early_stopping:
    value: true
  patience:
    value: 1000
