parameters:
  max_history:
    value: 20
  dimension:
    value: 1
  lengthscale:
    value: 0.05
  method:
    values: ['gittins', 'mse_ei']
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.00e-02
  train_samples_size:
    values: [100, 1000, 10000]
  layer_width:
    value: 300
  epochs:
    value: 1000
  learning_rate:
    values: [3.00e-07, 1.00e-05, 3.00e-04, 1.00e-02]
  batch_size:
    value: 512
  lr_scheduler:
    values: [null, 'ReduceLROnPlateau']
  lr_scheduler_patience:
    value: 15 # 45
  lr_scheduler_factor:
    value: 0.1 # 0.3
  early_stopping:
    value: true
  patience:
    value: 60 # 120
