parameters:
  method:
    values: ['gittins', 'mse_ei']
    recurse: true
  train_samples_size:
    values: all
  layer_width:
    values: [500]
  dimension:
    values: all
  patience:
    value: 20
