parameters:
  max_history:
    value: 100
  dimension:
    value: 6
  lengthscale:
    value: 0.2
  method:
    values: ['gittins', 'mse_ei']
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.e-3
  train_samples_size:
    value: 10000
  layer_width:
    value: 300
  learning_rate:
    values: [1.e-5, 1.e-3, 1.e-2]
  batch_size:
    value: 256
  lr_scheduler:
    value: ReduceLROnPlateau
