parameters:
  max_history:
    value: 20
  dimension:
    value: 1
  lengthscale:
    value: 0.05
  method:
    value: mse_ei
  train_samples_size:
    value: 10000
  layer_width:
    value: 300
  epochs:
    value: 1000
  learning_rate:
    values: [5.20e-05, 3.00e-04, 1.73e-03]
  batch_size:
    value: 512
  lr_scheduler:
    values: [null, 'ReduceLROnPlateau']
  lr_scheduler_patience:
    value: 50
  lr_scheduler_factor:
    value: 0.3
  early_stopping:
    value: true
  patience:
    value: 250
