parameters:
  dataset_type:
    value: logistic_regression
  method:
    value: gittins
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.e-2
  train_samples_size:
    value: 100  # Small for testing
  test_samples_size:
    value: 50   # Small for testing
  train_acquisition_size:
    value: 200  # Small for testing
  layer_width:
    value: 200
  learning_rate:
    value: 3.e-4
  patience:
    value: 30
  batch_size:
    value: 32
  epochs:
    value: 3  # Very few epochs for quick testing
  early_stopping:
    value: true
  train_n_candidates:
    value: 3
  test_n_candidates:
    value: 5
  min_history:
    value: 1
  max_history:
    value: 3
  # Logistic regression specific parameters
  lr_n_samples_range:
    value: [20, 100]  # Small range for testing
  lr_n_features_range:
    value: [2, 10]    # Small range for testing
  lr_bias_range:
    value: [-1.0, 1.0]
  lr_coefficient_std:
    value: 1.0
  lr_noise_range:
    value: [0.1, 0.5]
  lr_log_lambda_range:
    value: [-4, 0]    # Smaller range for testing
  lr_log_uniform_sampling:
    value: false