parameters:
  max_history:
    value: 20
  dimension:
    value: 1
  lengthscale:
    value: 0.05
  method:
    value: mse_ei
  train_samples_size:
    value: 10000
  layer_width:
    value: 300
  epochs:
    value: 7500
  learning_rate:
    value: 3.00e-04
  batch_size:
    value: 512
  lr_scheduler:
    values: [null, 'ReduceLROnPlateau']
  lr_scheduler_patience:
    value: 500
  lr_scheduler_factor:
    value: 0.5
  early_stopping:
    value: false
