parameters:
  max_history:
    value: 20
  dimension:
    value: 8
  lengthscale:
    value: 0.49
  method:
    value: policy_gradient
  train_samples_size:
    values: [2560]
  samples_addition_amount:
    values: [4000]
  test_samples_size:
    value: 1000
  test_expansion_factor:
    value: 100
  layer_width:
    values: [16, 32]
  architecture:
    value: pointnet
  include_best_y:
    values: [false, true]
  x_cand_input:
    values:
    - "local_only"
    - "local_and_final"
    - "subtract-lossy"
    - "subtract-final_only"
  dropout:
    values: [null]
  epochs:
    value: 10000
  learning_rate:
    values: [3.00e-04, 7.20e-04, 1.73e-03]
  batch_size:
    value: 512
  weight_decay:
    values: [1.00e-04]
  lr_scheduler:
    value: null
  lr_scheduler_patience:
    value: 300
  lr_scheduler_factor:
    value: 0.7
  early_stopping:
    value: false
  patience:
    value: 5000
  min_delta:
    value: 1.00e-09
