parameters:
  max_history:
    value: 20
  min_history:
    value: 1
  dimension:
    value: 1
  lengthscale:
    value: 0.05
  method:
    value: gittins
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.e-2
  layer_width:
    value: 200
  train_samples_size:
    value: 10000
  train_acquisition_size:
    value: 8192
  test_expansion_factor:
    value: 1
  test_samples_size:
    value: 5000
  layer_width:
    value: 200
  learning_rate:
    value: 3.e-4
  epochs:
    value: 500
  batch_size:
    value: 512
  lr_scheduler:
    value: ReduceLROnPlateau
  lr_scheduler_patience:
    value: 15
  lr_scheduler_factor:
    value: 0.1
  early_stopping:
    value: true
  patience:
    value: 30
