parameters:
  method:
    value: gittins
  gi_loss_normalization:
    value: normal
  lamda:
    value: 1.e-4
  train_samples_size:
    value: 10000
  layer_width:
    value: 200
  dimension:
    value: 16
  learning_rate:
    value: 3.e-5
  patience:
    value: 30
